### ISSUE TITLE
dmoz.csv missing / csv generator

### ISSUE THREAD

**Issue by ghost** [bhargavyagnik/web-classifier#1]
Hi,

Hope you are all well !

I wanted to try your web classifier in a google colab but the dmoz.csv file is missing. Can you provide it or the script to generate it ?

Thanks in advance for any insights or inputs on this.

Cheers,
Luc

**Comment by bhargavyagnik** [comment]
Hello,
Glad you asked me .. sorry I forgot to update that information on Github readme
But yeah I got it from official DMOZ site at [http://rdf.dmoz.org/] but this is down as DMOZ is closed permanently and the site is archived.
So you can use this link of my google drive to download the CSV or directly use the Kaggle dataset that contains only 5-6 classes

- Drive link for the same dataset used by me (credits to DMOZ.COM)  
[DMOZ dataset used by me](https://drive.google.com/open?id=1EaieHk05sdYpQpA3xIJCDy99qleoBs7p)

- Here's the link to Kaggle...
[Kaggle Dataset with 5 classes](https://www.kaggle.com/shawon10/url-classification-dataset-dmoz/version/2?select=dmoz.csv )

Good Luck,
Bhargav
